### ISSUE TITLE
Logo Proposal for MyReads

### ISSUE THREAD

**Issue by zuurw** [DownTheMatrix/MyReads-Book-Tracking-App#1]
Hi @DownTheMatrix I think that this app it´s brilliant, it's something someone who likes to read like me wants to have.
My name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project.  If it's something you're interested in, please, let me know!

Best Regards
Zuur

**Comment by DownTheMatrix** [comment]
Hi @zuurw, thanks for the message and the kind review. I would definitely be interested in seeing your logo proposal! You can send them over whenever you feel like :)

Best,
Bruno

**Comment by zuurw** [comment]
Hi @DownTheMatrix, do you have any request for the logo? do you have something in your mind? Can you give me something to I get inspired?

Best Regards!

**Comment by zuurw** [comment]
Hi @DownTheMatrix, I create 3 designs for your project.

1st logo - I create 3 blocks that represent 3 books  (currently reading, want to read and read)

2nd logo - I create a open book that is a reference to currently reading and the other 2 pages are a reference to want to read and read.

3rd logo- I create a eyes with glasses that represent reading, the two semi circles of the eyes represent an open book.

And thats it!

best Regards!

![proposal](https://user-images.githubusercontent.com/40801473/43428514-8e1a42cc-9456-11e8-844e-b49c7d77d493.png)

**Comment by DownTheMatrix** [comment]
Hey @zuurw, thanks for the message, and for the great work! They all look very nice. I could use one of them as favicon to display on the browser tab (next to the title). 
Btw, do you do graphic design only, or do you program as well? It would be nice to join forces on an open source project :)

Best,

Bruno

**Comment by zuurw** [comment]
Hi @DownTheMatrix, I only do graphic design, if you have other project I can make also a logo.
So wich logo do you want? 1st, 2nd or 3rd? and what color do you want too?

Best Regards!

**Comment by DownTheMatrix** [comment]
Hi @zuurw, I would say that the "book" logo, the first one from the left, fits the theme color the best. That being said, they're all pretty nice, well done! If you want to further discuss, you can email me at: suija87@gmail.com, so I can close this issue. 

Thanks!

**Comment by zuurw** [comment]
Hi @DownTheMatrix , I will try to submit the logo files today. Best Regards!

**Comment by zuurw** [comment]
Hi @DownTheMatrix, I sumited the logo files now, see if you want something else.

Best Regards!
